routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;
use GuzzleHttp\Client;

Auth::routes();

Route::resource('posts', 'PostsController');

Route::resource('comments', 'CommentsController', ['only' => ['store', 'destroy']]);

Route::get('/', 'PostsController@index')->name('home');

Route::get('/feed', 'HomeController@feed')->name('feed');

Route::get('/about', 'HomeController@about')->name('about');

Route::get('/api-posts', function (GuzzleHttp\Client $client){
	$response = $client->request('GET', "posts");
	$data = json_decode($response->getBody());
	return json_encode($data);
});

Route::group(['middleware' => 'auth'], function() {
	Route::resource('users', 'UsersController', ['only' => ['show','create','edit', 'update']]);
});

Route::group(['prefix' => 'auth'], function () {
	Route::get('{provider}', 'Auth\AuthController@redirectToProvider')->name('auth.provider');
	Route::get('{provider}/callback', 'Auth\AuthController@handleProviderCallback');
});

app/Post.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Post extends Model
{
	protected $fillable = [
		'author_id',
		'title',
		'content'
	];

	public $dates = [ 'created_at' ];

	/**
	 * @param $query
	 * @param int $limit
	 * @return mixed
	 */
	public static function lastMonth($query, int $limit = 5) {
		return $query->whereBetween('created_at', Carbon::now()->subMonth())
			->orderBy('posted_at', 'desc')
			->limit($limit);
	}

	/**
	 * @return BelongsTo
	 */
	public function author() {
		return $this->belongsTo('App\User', 'author_id');
	}

//	/**
//	 * Get the route key for the model.
//	 *
//	 * @return string
//	 */
//	public function getRouteKeyName() {
//		return 'slug';
//	}


	/**
	 * @return HasMany
	 */
	public function comments() {
		return $this->hasMany('App\Comment');
	}
}

app/Http/Controllers/PostsController.php
<?php

namespace App\Http\Controllers;

use App\Post;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Auth;

class PostsController extends Controller {
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index() {
		$posts = Post::orderBy('created_at', 'desc')->paginate(2);
		return view('welcome')->withPosts($posts);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create() {
        return view('posts.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return Response
     */
    public function store(Request $request) {
		if (Auth::check()) {
			$user = Auth::user();
			$post = new Post($request->all());
			$post->author_id= $user->getAuthIdentifier();
			$post->save();
			$comments = $post->comments()->orderBy('created_at', 'desc')->paginate(15);
			return view('posts.show')->withPost($post)->withComments($comments);
		}else{
			abort(403, 'Unauthorized action.');
		}
	}

    /**
     * Display the specified resource.
     *
     * @param Post $post
     * @return Response
     */
    public function show(Post $post) {
		$comments = $post->comments()->orderBy('created_at', 'desc')->paginate(15);
		return view('posts.show')->withPost($post)->withComments($comments);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Post $post
     * @return Response
     */
    public function edit() {
       
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param Post $post
     * @return Response
     */
    public function update() {
    	
    }

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param $id
	 * @return Response
	 */
    public function destroy() {

 
    }
}

resources/views/posts/create.blade.php
@extends('layouts.app')

@section('content')

	<div class="container">
	<div class="row">
		<h1 class="modal-title">Create new Post</h1>
		<div class="col-md-8 offset-md-2">
		<form method="POST" action="/posts">
			{{ csrf_field() }}

			<div class="form-group">
				<label for="title" >Post Title:</label>
				<input type="text" name="title" id="title" class="form-control" placeholder="Enter Post Title Here..">
			</div>
			<div class="form-group">
				<label for="content" >Post Content:</label>
				<textarea name="content" id="content" cols="30" rows="10" class="form-control" placeholder="Enter Post Content Here.."></textarea>
			</div>
			<button type="submit" class="btn btn-primary">Submit</button>
		</form>
		</div>
	</div>
	</div>
@endsection

resources/views/posts/show.blade.php
@extends('layouts.app')
@section('content')

	<div class="container">
		<div class="row">

			@if (Session::has('success'))
				<div class="alert alert-success alert-dismissible w-100" role="alert">
					<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					{{ Session::get('success') }}
				</div>
			@endif

			<div class="col-md-10 offset-md-1">
				<div class="container clearfix">
					<h1 class="float-left">
					{{ $post->title }}
					</h1>
					<br>
					<br>

					<div class="meta-info">
						<p class="float-right">
							Posted By: <a href="{{ route('users.show', $post->author ) }}" class="font-weight-bold">{{ user_name($post->author) }}</a>
							on <i>{{  humanize_date($post->created_at) }}</i>
						</p>
					</div>
				</div>
		
				<hr />
				<div class="p">
					{{ $post->content }}
				</div>
				<hr>
				<div class="container">
					@include ('comments._list')
				</div>
			</div>
		</div>
	</div>
@endsection